-- Up Migration
-- Per-card nudge copy for the Warmth-bot stale-plan reminder. When a couple
-- approves a plan but hasn't marked it done after 3 days, the scheduler posts
-- this line (as the Warmth bot) into the plan's comment thread. Keyed by id:
-- titles aren't unique (a few dupes), but ids are stable across environments
-- (cards are seeded in fixed migration order). Cards without a line here
-- (future seeds, couple-created customs) fall back to a generic template built
-- from the title in the scheduler.
ALTER TABLE activities ADD COLUMN IF NOT EXISTS nudge_text TEXT;

UPDATE activities SET nudge_text = $$You both said yes to horseback riding by the sea. The horses (and that breeze) are still waiting — pick a day? 🐴$$ WHERE id = 1;
UPDATE activities SET nudge_text = $$Kayaking at sunrise is still on your list. Set the alarm one morning — it's worth it. 🌅$$ WHERE id = 2;
UPDATE activities SET nudge_text = $$That viewpoint isn't going anywhere, but the two of you should. When are you hiking up? ⛰️$$ WHERE id = 3;
UPDATE activities SET nudge_text = $$You both wanted to catch waves. Book the surf lesson — falling in is half the fun. 🏄$$ WHERE id = 4;
UPDATE activities SET nudge_text = $$Zip-lining is still waiting for your brave yes. Don't overthink it — just pick a date. 🌲$$ WHERE id = 5;
UPDATE activities SET nudge_text = $$There's a whole world under the water you two said yes to. When are you going in? 🐠$$ WHERE id = 6;
UPDATE activities SET nudge_text = $$You both agreed on a movie night. Blankets, popcorn, just you two — what night works? 🍿$$ WHERE id = 7;
UPDATE activities SET nudge_text = $$That picnic is still just an idea. Pick a sunny afternoon and pack the basket. 🧺$$ WHERE id = 8;
UPDATE activities SET nudge_text = $$You said yes to a sunset, no phones. The sky does this every evening — claim one. 🌇$$ WHERE id = 9;
UPDATE activities SET nudge_text = $$Two books, one couch — you both wanted it. Tonight? 📚$$ WHERE id = 10;
UPDATE activities SET nudge_text = $$An afternoon of doing nothing, perfectly. You earned it — when? 🌿$$ WHERE id = 11;
UPDATE activities SET nudge_text = $$You both wanted an aimless evening walk. No plan needed — just shoes and each other. 🌙$$ WHERE id = 12;
UPDATE activities SET nudge_text = $$You said yes to getting your hands messy. Book the pottery class — wobbly bowls welcome. 🏺$$ WHERE id = 13;
UPDATE activities SET nudge_text = $$No talent required, you agreed. Get the paints out — when's your colorful evening? 🎨$$ WHERE id = 14;
UPDATE activities SET nudge_text = $$You both wanted to travel through taste. Spin the globe and pick a kitchen night. 🌍$$ WHERE id = 15;
UPDATE activities SET nudge_text = $$You said yes to seeing your city new. Grab a camera and wander — which day? 📸$$ WHERE id = 16;
UPDATE activities SET nudge_text = $$Letters to your future selves, you both agreed. Write them this week and seal them. 💌$$ WHERE id = 17;
UPDATE activities SET nudge_text = $$A shelf, a birdhouse, a memory — you said yes. What are you building, and when? 🔨$$ WHERE id = 18;
UPDATE activities SET nudge_text = $$You both signed up to draw each other. The results will be terrible and perfect — go. ✏️$$ WHERE id = 19;
UPDATE activities SET nudge_text = $$You agreed to step on each other's toes. Put music on and start — tonight? 💃$$ WHERE id = 20;
UPDATE activities SET nudge_text = $$Pick a direction and go, you said. Which weekend has your names on it? 🚗$$ WHERE id = 21;
UPDATE activities SET nudge_text = $$Be tourists in your own city — you both wanted this. Pick a neighborhood and roam. 🗺️$$ WHERE id = 22;
UPDATE activities SET nudge_text = $$Just a tent and each other, you agreed. When are you sleeping under the stars? ⛺$$ WHERE id = 23;
UPDATE activities SET nudge_text = $$A cabin weekend to disconnect — you both said yes. Book it before life fills the calendar. 🌲$$ WHERE id = 24;
UPDATE activities SET nudge_text = $$Sand, water, nothing to do — you wanted it. Which day are you stealing? 🏖️$$ WHERE id = 25;
UPDATE activities SET nudge_text = $$Get lost on purpose, you agreed. Pick a town off the map and just go. 🚏$$ WHERE id = 26;
UPDATE activities SET nudge_text = $$Five quiet minutes before the day — you said yes. Tomorrow morning, just you two? ☕$$ WHERE id = 27;
UPDATE activities SET nudge_text = $$You wanted to surprise them with lunch. A small thing that says everything — do it this week. 🥡$$ WHERE id = 28;
UPDATE activities SET nudge_text = $$Breakfast in bed was the plan. Pick a slow morning and bring the tray. 🍳$$ WHERE id = 29;
UPDATE activities SET nudge_text = $$You meant to leave a note they'd keep. A few words, today — don't wait. 📝$$ WHERE id = 30;
UPDATE activities SET nudge_text = $$The best talks happen on an after-dinner walk. You both agreed — tonight? 🌆$$ WHERE id = 31;
UPDATE activities SET nudge_text = $$Side by side in the kitchen, you said yes. What's for dinner, and which night? 🍳$$ WHERE id = 32;
UPDATE activities SET nudge_text = $$You don't need a restaurant, you agreed. Light the candles at home — pick the evening. 🕯️$$ WHERE id = 33;
UPDATE activities SET nudge_text = $$City lights and conversation — you both wanted it. Find a rooftop and a free night. 🌃$$ WHERE id = 34;
UPDATE activities SET nudge_text = $$You said yes to finding your star. Wait for a clear night and look up together. ✨$$ WHERE id = 35;
UPDATE activities SET nudge_text = $$You both wanted to unwind in the same room. Book the massage — your shoulders agree. 💆$$ WHERE id = 36;
UPDATE activities SET nudge_text = $$Play your song and slow dance — you agreed. No audience needed. Tonight? 💕$$ WHERE id = 37;
UPDATE activities SET nudge_text = $$Flowers for no reason — you meant to. No reason is the best reason. Send them this week. 💐$$ WHERE id = 38;
UPDATE activities SET nudge_text = $$Hot cocoa and fairy lights — you both said yes. The market's waiting; pick an evening. 🎄$$ WHERE id = 39;
UPDATE activities SET nudge_text = $$A bonfire on the beach, you agreed. Summer nights are made for this — when? 🔥$$ WHERE id = 40;
UPDATE activities SET nudge_text = $$Golden paths together — you wanted it. The leaves won't wait long; take the walk. 🍂$$ WHERE id = 41;
UPDATE activities SET nudge_text = $$Hold hands and don't let go, you said. Lace up — which day are you wobbling out there? ⛸️$$ WHERE id = 42;
UPDATE activities SET nudge_text = $$A field full of color was the plan. Spring's brief — go before it fades. 🌷$$ WHERE id = 43;
UPDATE activities SET nudge_text = $$Messy hands, sweet result — you both agreed. What are you baking, and when? 🧁$$ WHERE id = 44;
UPDATE activities SET nudge_text = $$You said yes to finding what you both love. Pour a few and taste together — pick a night. 🍷$$ WHERE id = 45;
UPDATE activities SET nudge_text = $$Roll, laugh, eat — you wanted it. Get the rice going one evening this week. 🍣$$ WHERE id = 46;
UPDATE activities SET nudge_text = $$Pick tonight's ingredients together, you said. Which morning are you wandering the stalls? 🥕$$ WHERE id = 47;
UPDATE activities SET nudge_text = $$Adventure on a plate — you both agreed. Find the place neither of you has tried. 🍜$$ WHERE id = 48;
UPDATE activities SET nudge_text = $$Wind in your hair, side by side — you said yes. Roll the bikes out one of these days. 🚲$$ WHERE id = 49;
UPDATE activities SET nudge_text = $$Breathe together, you agreed. Roll out two mats tomorrow morning. 🧘$$ WHERE id = 50;
UPDATE activities SET nudge_text = $$Play, don't compete — you both wanted it. Grab the rackets this week. 🎾$$ WHERE id = 51;
UPDATE activities SET nudge_text = $$Warm water, golden light — you said yes. Pick an evening and dive in. 🏊$$ WHERE id = 52;
UPDATE activities SET nudge_text = $$Trust each other on the wall, you agreed. Book the climb — belay each other. 🧗$$ WHERE id = 53;
UPDATE activities SET nudge_text = $$You meant to make each other's favorite drink. Small gesture, big warmth — do it today. ☕$$ WHERE id = 54;
UPDATE activities SET nudge_text = $$Just you two at the table, you agreed. Phones away — which dinner is it? 🍽️$$ WHERE id = 55;
UPDATE activities SET nudge_text = $$Start the day held, you both said. Tomorrow morning, five minutes, no rush. 🤗$$ WHERE id = 56;
UPDATE activities SET nudge_text = $$Low stakes, sweet ideas — you wanted a tea-and-planning evening. Put the kettle on. 🍵$$ WHERE id = 57;
UPDATE activities SET nudge_text = $$Five songs each, you agreed. Trade what moves you — make the playlist this week. 🎧$$ WHERE id = 58;
UPDATE activities SET nudge_text = $$Soft light, slow talk — you both said yes. Light them tonight and turn the rest off. 🕯️$$ WHERE id = 59;
UPDATE activities SET nudge_text = $$Make the future visible, you agreed. Cut, paste, dream — pick an afternoon. ✂️$$ WHERE id = 60;
UPDATE activities SET nudge_text = $$Rhyme badly, laugh hard — you both wanted to. Grab a pen and be ridiculous. 🎵$$ WHERE id = 61;
UPDATE activities SET nudge_text = $$Change the space, shift the mood — you said yes. Pick a room and move things. 🛋️$$ WHERE id = 62;
UPDATE activities SET nudge_text = $$Return to where it started, you both agreed. Recreate the first date — which evening? 💞$$ WHERE id = 63;
UPDATE activities SET nudge_text = $$Old words, new meaning — you wanted it. Read a few lines aloud tonight. 📖$$ WHERE id = 64;
UPDATE activities SET nudge_text = $$Be the one who plans it, you agreed. Surprise them — your turn to lead. 🎁$$ WHERE id = 65;
UPDATE activities SET nudge_text = $$A sweet route through the city — you said yes. Three spots, one evening. When? 🍰$$ WHERE id = 66;
UPDATE activities SET nudge_text = $$Taste by taste, together — you both wanted it. Build the board this week. 🧀$$ WHERE id = 67;
UPDATE activities SET nudge_text = $$Invent a drink and name it, you agreed. Shake something up one evening. 🍸$$ WHERE id = 68;
UPDATE activities SET nudge_text = $$Footprints in the quiet — you said yes. When the snow comes, take the walk. ❄️$$ WHERE id = 69;
UPDATE activities SET nudge_text = $$The longest golden evening — you both wanted it. Eat outside as the light lingers. 🌅$$ WHERE id = 70;
UPDATE activities SET nudge_text = $$Childish joy, fully adult — you agreed. Hide a few eggs and play. 🥚$$ WHERE id = 71;
UPDATE activities SET nudge_text = $$Sweat and breath, side by side — you said yes. Tomorrow morning, two pairs of shoes. 🏃$$ WHERE id = 72;
UPDATE activities SET nudge_text = $$Step, laugh, step again — you both wanted it. Book the class this week. 💃$$ WHERE id = 73;
UPDATE activities SET nudge_text = $$Balance on quiet water, you agreed. Find a calm morning and paddle out. 🏄$$ WHERE id = 74;
UPDATE activities SET nudge_text = $$Let them lead the whole day, you said. Hand over the plans — when? 🙌$$ WHERE id = 75;
UPDATE activities SET nudge_text = $$Dream on paper for an hour, you agreed. Open a map and start scheming. ✈️$$ WHERE id = 76;
UPDATE activities SET nudge_text = $$Get off wherever feels right, you both wanted. Hop a train this weekend. 🚆$$ WHERE id = 77;
UPDATE activities SET nudge_text = $$Sunrise from above — you said yes. Book the balloon; the view's worth the early alarm. 🎈$$ WHERE id = 78;
UPDATE activities SET nudge_text = $$Learn the wind together, you agreed. Book the lesson — set sail. ⛵$$ WHERE id = 79;
UPDATE activities SET nudge_text = $$Silence and blue, shared — you both wanted it. Book the dive and breathe underwater together. 🤿$$ WHERE id = 80;
UPDATE activities SET nudge_text = $$No list, just wander and pick, you said. Spend an aimless hour together. 🛍️$$ WHERE id = 81;
UPDATE activities SET nudge_text = $$Walk into the earth together, you agreed. Book the cave tour — bring a light. 🔦$$ WHERE id = 82;
UPDATE activities SET nudge_text = $$Paddle through the rush, you both said yes. Book the raft before the season ends. 🚣$$ WHERE id = 83;
UPDATE activities SET nudge_text = $$Float above it all, you wanted to. Pick a clear day and run off the hill. 🪂$$ WHERE id = 84;
UPDATE activities SET nudge_text = $$Wheels, dirt, laughter — you agreed. Hit the trail one of these weekends. 🚵$$ WHERE id = 85;
UPDATE activities SET nudge_text = $$Dust and speed together, you said yes. Book the ride and get muddy. 🏍️$$ WHERE id = 86;
UPDATE activities SET nudge_text = $$Wind in your hands, you both wanted it. Bring a kite to the coast on a breezy day. 🪁$$ WHERE id = 87;
UPDATE activities SET nudge_text = $$Climb side by side, secured — you agreed. Book the route and trust the cable. 🧗$$ WHERE id = 88;
UPDATE activities SET nudge_text = $$Salt spray, shared speed — you said yes. Rent the jetski one warm day. 🌊$$ WHERE id = 89;
UPDATE activities SET nudge_text = $$Slow pieces, soft talk — you both wanted it. Dump the box out this weekend. 🧩$$ WHERE id = 90;
UPDATE activities SET nudge_text = $$Watch it bloom together, you agreed. Make the slow coffee one quiet morning. ☕$$ WHERE id = 91;
UPDATE activities SET nudge_text = $$Let the world pause, you said yes. Next rainy day is yours — no plans. 🌧️$$ WHERE id = 92;
UPDATE activities SET nudge_text = $$Lose on purpose sometimes, you agreed. Pick a game and a night. 🎲$$ WHERE id = 93;
UPDATE activities SET nudge_text = $$Remember the small moments, you both wanted it. Curl up and scroll back tonight. 📷$$ WHERE id = 94;
UPDATE activities SET nudge_text = $$Silly look, real calm — you said yes. Slap the masks on this week. 🧖$$ WHERE id = 95;
UPDATE activities SET nudge_text = $$Warm water, slow songs — you agreed. Run the bath one evening. 🛁$$ WHERE id = 96;
UPDATE activities SET nudge_text = $$Learn something side by side, you wanted to. Pick one and press play tonight. 🎬$$ WHERE id = 97;
UPDATE activities SET nudge_text = $$Flour everywhere, perfect mess — you both said yes. Roll the dough this week. 🍝$$ WHERE id = 98;
UPDATE activities SET nudge_text = $$Something you'll grow together, you agreed. Pot a few herbs this weekend. 🌱$$ WHERE id = 99;
UPDATE activities SET nudge_text = $$Slow ink, steady hands — you wanted it. Pick up the pens one quiet evening. ✒️$$ WHERE id = 100;
UPDATE activities SET nudge_text = $$Fool each other, laugh anyway — you both agreed. Learn one trick each this week. 🎩$$ WHERE id = 101;
UPDATE activities SET nudge_text = $$Paper, patience, pride — you said yes. Fold something tonight. 🦢$$ WHERE id = 102;
UPDATE activities SET nudge_text = $$Return to being children, you wanted to. Build the fort tonight — pillows included. 🏰$$ WHERE id = 103;
UPDATE activities SET nudge_text = $$Curate your year together, you agreed. Pick the photos one cozy evening. 📔$$ WHERE id = 104;
UPDATE activities SET nudge_text = $$Dreams on one page — you both said yes. Write the list together this week. 📜$$ WHERE id = 105;
UPDATE activities SET nudge_text = $$Warm water, no rush — you agreed. No reason to wait. 🚿$$ WHERE id = 106;
UPDATE activities SET nudge_text = $$Just you two, slowly waking — you said yes. Try it tomorrow — phones can wait. 🌅$$ WHERE id = 107;
UPDATE activities SET nudge_text = $$Notice out loud today, you agreed. Three small things — tell them. 💬$$ WHERE id = 108;
UPDATE activities SET nudge_text = $$A minute of your voice, you wanted to. Send one at lunch today. 🎙️$$ WHERE id = 109;
UPDATE activities SET nudge_text = $$A small act of care, you said yes. Pack their lunch tomorrow morning. 🥪$$ WHERE id = 110;
UPDATE activities SET nudge_text = $$Eyes closed, close together — you agreed. Five quiet minutes, today. 🧘$$ WHERE id = 111;
UPDATE activities SET nudge_text = $$Then really listen, you said. Ask tonight — and stay for the answer. 👂$$ WHERE id = 112;
UPDATE activities SET nudge_text = $$Music and presence, you both wanted it. Take the quiet drive this week. 🚙$$ WHERE id = 113;
UPDATE activities SET nudge_text = $$Your dough, your toppings, you agreed. Which night is pizza night? 🍕$$ WHERE id = 114;
UPDATE activities SET nudge_text = $$A Sunday tradition starts here, you said yes. Pick the spot for this weekend. 🥞$$ WHERE id = 115;
UPDATE activities SET nudge_text = $$Three scoops, three streets — you both wanted it. Pick a warm evening. 🍦$$ WHERE id = 116;
UPDATE activities SET nudge_text = $$Cup by cup, together — you agreed. Start the tour this weekend. ☕$$ WHERE id = 117;
UPDATE activities SET nudge_text = $$Build, share, mess up — you said yes. Taco night — which evening? 🌮$$ WHERE id = 118;
UPDATE activities SET nudge_text = $$Dip, talk, repeat — you both wanted it. Melt the cheese one night soon. 🫕$$ WHERE id = 119;
UPDATE activities SET nudge_text = $$Dark, milk, salted, sweet — you agreed. Line them up and taste this week. 🍫$$ WHERE id = 120;
UPDATE activities SET nudge_text = $$Kneaded with patience, you said yes. Start the dough one slow morning. 🍞$$ WHERE id = 121;
UPDATE activities SET nudge_text = $$Say it in ink first, you both agreed. Write them and read aloud this week. 💌$$ WHERE id = 122;
UPDATE activities SET nudge_text = $$Soft light, skin close — you wanted it. Run the bath, light the candles. 🕯️$$ WHERE id = 123;
UPDATE activities SET nudge_text = $$Stir, sway, kiss — you said yes. Put music on next time you cook. 💃$$ WHERE id = 124;
UPDATE activities SET nudge_text = $$Meet the kid they were, you agreed. Pull out the old photos tonight. 👶$$ WHERE id = 125;
UPDATE activities SET nudge_text = $$No alarm, no agenda — you both wanted it. Claim a slow morning this weekend. ☕$$ WHERE id = 126;
UPDATE activities SET nudge_text = $$An hour of soft things, you said yes. Trade kind words tonight. 💗$$ WHERE id = 127;
UPDATE activities SET nudge_text = $$Look at each other again, you agreed. Dress up tonight — no occasion needed. 👗$$ WHERE id = 128;
UPDATE activities SET nudge_text = $$Warm air, warmer hands — you wanted it. Take the drive this golden hour. 🌇$$ WHERE id = 129;
UPDATE activities SET nudge_text = $$Silly faces, real fun — you both said yes. Grab a pumpkin and carve this week. 🎃$$ WHERE id = 130;
UPDATE activities SET nudge_text = $$Splash, float, nap — you agreed. Pick a hot day and head to the lake. 🏞️$$ WHERE id = 131;
UPDATE activities SET nudge_text = $$Fall backwards, laugh up — you wanted it. First good snow, get out there. ❄️$$ WHERE id = 132;
UPDATE activities SET nudge_text = $$Lighten the house together, you said yes. Pick a Saturday and clear it out. 🧹$$ WHERE id = 133;
UPDATE activities SET nudge_text = $$Lights over the city, you both agreed. Find a rooftop for the next show. 🎆$$ WHERE id = 134;
UPDATE activities SET nudge_text = $$Crisp air, full basket — you wanted it. Go before the season's over. 🍎$$ WHERE id = 135;
UPDATE activities SET nudge_text = $$Warm bowl, warm blanket — you said yes. Simmer something and pick a film. 🍲$$ WHERE id = 136;
UPDATE activities SET nudge_text = $$Pink sky, slow steps — you agreed. The blossoms are brief — go now. 🌸$$ WHERE id = 137;
UPDATE activities SET nudge_text = $$Fast hands, soft rivalry — you both wanted it. Set up the table this week. 🏓$$ WHERE id = 138;
UPDATE activities SET nudge_text = $$Stretch side by side, you said yes. Book the class — bring two mats. 🧘$$ WHERE id = 139;
UPDATE activities SET nudge_text = $$Gloves on, smile wider — you agreed. Book it and throw a few punches together. 🥊$$ WHERE id = 140;
UPDATE activities SET nudge_text = $$Same pace, same breath — you wanted it. Pick a route and run it together. 🏃$$ WHERE id = 141;
UPDATE activities SET nudge_text = $$Wet boots, bright mood — you both said yes. Next drizzle, lace up. 🌧️$$ WHERE id = 142;
UPDATE activities SET nudge_text = $$Gutter balls and high-fives — you agreed. Book a lane this week. 🎳$$ WHERE id = 143;
UPDATE activities SET nudge_text = $$Windmills and kisses — you said yes. Pick an evening for eighteen silly holes. ⛳$$ WHERE id = 144;
UPDATE activities SET nudge_text = $$Bounce until you're kids again, you wanted it. Book an hour this weekend. 🤸$$ WHERE id = 145;
UPDATE activities SET nudge_text = $$Same country, new bed — you both agreed. Book a random night away. 🛏️$$ WHERE id = 146;
UPDATE activities SET nudge_text = $$Board the next cheap flight, you said yes. Dare each other to actually do it. ✈️$$ WHERE id = 147;
UPDATE activities SET nudge_text = $$Wake up somewhere new, you wanted it. Pick a small town and ride out. 🚌$$ WHERE id = 148;
UPDATE activities SET nudge_text = $$Stand where land ends, you agreed. Find a lighthouse and drive out. 🗼$$ WHERE id = 149;
UPDATE activities SET nudge_text = $$Warm stones, slow hours — you both said yes. Book the spa weekend before life crowds in. 💆$$ WHERE id = 150;
UPDATE activities SET nudge_text = $$Stumble in a new tongue, you wanted it. Pick a language and a weekend. 🗣️$$ WHERE id = 151;
UPDATE activities SET nudge_text = $$Warm hands, warmer talk — you agreed. Find the coziest cafe this week. ☕$$ WHERE id = 152;
UPDATE activities SET nudge_text = $$Sticky fingers, sweet chaos — you said yes. Build it this week — frosting everywhere. 🏠$$ WHERE id = 153;
UPDATE activities SET nudge_text = $$No agenda, just quiet — you wanted it. Next snowfall, two cups of tea. 🍵$$ WHERE id = 154;
UPDATE activities SET nudge_text = $$Bundled up, glowing streets — you both agreed. Take the walk this week. ✨$$ WHERE id = 155;
UPDATE activities SET nudge_text = $$Classic, silly, required — you said yes. First good snow is yours. ⛄$$ WHERE id = 156;
UPDATE activities SET nudge_text = $$Kid-mode, full speed — you wanted it. Grab a sled next snowy day. 🛷$$ WHERE id = 157;
UPDATE activities SET nudge_text = $$Slow evening, soft light — you agreed. Light the fire, pour two glasses. 🔥$$ WHERE id = 158;
UPDATE activities SET nudge_text = $$Snow, lift, lodge — you both said yes. Book the ski weekend while there's snow. 🎿$$ WHERE id = 159;
UPDATE activities SET nudge_text = $$Crisp sky, cold noses — you wanted it. Bundle up and look up one clear night. 🌌$$ WHERE id = 160;
UPDATE activities SET nudge_text = $$Begin it right, you agreed. Plan where you'll be at midnight. 🥂$$ WHERE id = 161;
UPDATE activities SET nudge_text = $$Somewhere neither of you has been, you said yes. Start with one date and a flight search. 🌍$$ WHERE id = 162;
UPDATE activities SET nudge_text = $$Lay it all out together, you agreed — no last-minute panic. Do it the night before. 🧳$$ WHERE id = 163;
UPDATE activities SET nudge_text = $$Hello, thank you, two beers please — you wanted to. Learn five before you go. 🗣️$$ WHERE id = 164;
UPDATE activities SET nudge_text = $$Three places each, you said yes. Compare lists this week. 🗺️$$ WHERE id = 165;
UPDATE activities SET nudge_text = $$Find the spot before you land, you agreed. Pick where you'll eat first. 🍽️$$ WHERE id = 166;
UPDATE activities SET nudge_text = $$Something small you'll see daily, you wanted it. Decide what you're hunting for. 🎁$$ WHERE id = 167;
UPDATE activities SET nudge_text = $$Anywhere two tanks of gas gets you — you said yes. Which weekend's the road trip? 🚗$$ WHERE id = 168;
UPDATE activities SET nudge_text = $$One song each, no skipping — you agreed. Build the playlist before you drive. 🎶$$ WHERE id = 169;
UPDATE activities SET nudge_text = $$Scenic lookouts and weird signs — you wanted it. Pick three stops for the drive. 📸$$ WHERE id = 170;
UPDATE activities SET nudge_text = $$Ten-minute grocery run, you said yes. Stock up before the road trip. 🍿$$ WHERE id = 171;
UPDATE activities SET nudge_text = $$A story from before you met, every hour — you agreed. Save them for the drive. 💭$$ WHERE id = 172;
UPDATE activities SET nudge_text = $$Off-grid, just the two of you — you said yes. Book the cabin before the calendar fills. 🌲$$ WHERE id = 173;
UPDATE activities SET nudge_text = $$The recipe you always scroll past, you wanted it. Make it this week. 🍳$$ WHERE id = 174;
UPDATE activities SET nudge_text = $$Lights off, blanket out, look up — you agreed. Pick a clear night. 🌟$$ WHERE id = 175;
UPDATE activities SET nudge_text = $$One reads, one listens — you said yes. One chapter tonight. 📖$$ WHERE id = 176;
UPDATE activities SET nudge_text = $$Both phones in another room, you agreed. Try it at the next dinner. 📵$$ WHERE id = 177;
UPDATE activities SET nudge_text = $$Pick one and practice for a week, you wanted it. Start tonight. 💃$$ WHERE id = 178;
UPDATE activities SET nudge_text = $$Three minutes, pick together, no second-guessing — you said yes. Choose it this week. 🎵$$ WHERE id = 179;
UPDATE activities SET nudge_text = $$Tiny daily rep, five days — you agreed. Start before tonight's dinner. ⏱️$$ WHERE id = 180;
UPDATE activities SET nudge_text = $$Phone on the counter, one try — you wanted it. Hit record this week. 🎥$$ WHERE id = 181;
UPDATE activities SET nudge_text = $$A friend, a parent, a post — you said yes. Share it once you've made it. 📲$$ WHERE id = 182;
UPDATE activities SET nudge_text = $$Choose a fragrance for each other, you agreed. Go sniff some this week. 🌸$$ WHERE id = 213;
UPDATE activities SET nudge_text = $$Five weird snacks, no peeking — you said yes. Set it up one evening. 🙈$$ WHERE id = 214;
UPDATE activities SET nudge_text = $$Fifteen euros, dress each other — you wanted it. Hit the thrift store this weekend. 👕$$ WHERE id = 215;
UPDATE activities SET nudge_text = $$Set the alarm, watch it rise — you agreed. Pick a clear morning and climb. 🌄$$ WHERE id = 216;
UPDATE activities SET nudge_text = $$The recipe from their childhood, you said yes. Make it for them this week. 🍲$$ WHERE id = 217;
UPDATE activities SET nudge_text = $$New streets, no map, no phones — you wanted it. Take the long walk this weekend. 🚶$$ WHERE id = 218;
UPDATE activities SET nudge_text = $$How to love me when I'm stressed, you agreed. Write them and swap. 📋$$ WHERE id = 219;
UPDATE activities SET nudge_text = $$Do the touristy thing at home, you said yes. Pick the day you play tourist. 🗺️$$ WHERE id = 220;
UPDATE activities SET nudge_text = $$Make a mess, make a bowl — you wanted it. Book the class this week. 🏺$$ WHERE id = 221;
UPDATE activities SET nudge_text = $$Thirty things to do together, you agreed. Write the list one evening soon. 📝$$ WHERE id = 222;
UPDATE activities SET nudge_text = $$Buy it fresh, make it together — you said yes. Market morning, then cook. 🥬$$ WHERE id = 223;
UPDATE activities SET nudge_text = $$Two wheels, golden hour — you wanted it. Ride out one evening this week. 🚲$$ WHERE id = 224;
UPDATE activities SET nudge_text = $$Blankets, fairy lights, one film — you agreed. Build it this weekend. 🏰$$ WHERE id = 225;
UPDATE activities SET nudge_text = $$Wobble together, laugh a lot — you said yes. Lace up this week. ⛸️$$ WHERE id = 226;
UPDATE activities SET nudge_text = $$Fill the kitchen with warmth, you wanted it. Start the dough one slow morning. 🥮$$ WHERE id = 227;
UPDATE activities SET nudge_text = $$Spiced, steaming, just you two — you agreed. Warm a pot this week. 🍷$$ WHERE id = 228;
UPDATE activities SET nudge_text = $$Warm hands around paper cups, you said yes. Go one cold morning. ☕$$ WHERE id = 229;
UPDATE activities SET nudge_text = $$Dream the year out loud, you wanted it. Light the fire and plan. 🔥$$ WHERE id = 230;
UPDATE activities SET nudge_text = $$Cocoa out in the cold, you agreed. Pack the thermos next snowy day. ❄️$$ WHERE id = 231;
UPDATE activities SET nudge_text = $$Heat, shock, a shared gasp — you said yes. Book it this week. 🧖$$ WHERE id = 232;
UPDATE activities SET nudge_text = $$Make it all glow, you wanted it. Pick an afternoon to deck it out. ✨$$ WHERE id = 233;
UPDATE activities SET nudge_text = $$Slow down and mean it, you agreed. Write a few together this week. 💌$$ WHERE id = 234;
UPDATE activities SET nudge_text = $$Camp without the cold, you said yes. Pitch the indoor tent tonight. 🏕️$$ WHERE id = 235;
UPDATE activities SET nudge_text = $$Two pots, one taste test — you wanted it. Have the cook-off this week. 🍲$$ WHERE id = 236;
UPDATE activities SET nudge_text = $$Catch the light on the ice, you agreed. Go out one frosty morning. 📸$$ WHERE id = 237;
UPDATE activities SET nudge_text = $$Robes, candles, no rush — you said yes. Make tonight the spa night. 🕯️$$ WHERE id = 238;
UPDATE activities SET nudge_text = $$Hot toddies, cocoa, cider — you wanted it. Mix a round this week. ☕$$ WHERE id = 239;
UPDATE activities SET nudge_text = $$Songs for short days, you agreed. Build it one cozy evening. 🎧$$ WHERE id = 240;
UPDATE activities SET nudge_text = $$Pajamas, popcorn, no plans — you said yes. Block out a lazy day. 🍿$$ WHERE id = 241;
UPDATE activities SET nudge_text = $$Winner picks the movie, you agreed. Book the track — loser buys snacks. 🏎️$$ WHERE id = 242;
UPDATE activities SET nudge_text = $$Surprisingly great date, you both said. Book it this week — bullseyes await. 🪓$$ WHERE id = 243;
UPDATE activities SET nudge_text = $$Beat the clock together, you wanted it. Book the room and start the timer. 🔐$$ WHERE id = 244;
UPDATE activities SET nudge_text = $$Survive it, laugh later — you agreed. Tackle the box this weekend. 🔧$$ WHERE id = 245;
UPDATE activities SET nudge_text = $$Low, slow, smoky — you said yes. Fire up the grill this weekend. 🍖$$ WHERE id = 246;
UPDATE activities SET nudge_text = $$Scoville ladder, milk on standby — you wanted it. Take the challenge this week. 🌶️$$ WHERE id = 247;
UPDATE activities SET nudge_text = $$One controller each, beat the boss — you agreed. Pick a night to play. 🎮$$ WHERE id = 248;
UPDATE activities SET nudge_text = $$Chase the aerial shot, you said yes. Find an open field this week. 🚁$$ WHERE id = 249;
UPDATE activities SET nudge_text = $$Bullseye for bragging rights, you wanted it. Best of five — when? 🎯$$ WHERE id = 250;
UPDATE activities SET nudge_text = $$Tokens, high scores, trash talk — you agreed. Hit the arcade this week. 🕹️$$ WHERE id = 251;
UPDATE activities SET nudge_text = $$Two minutes of pure flight, you said yes. Book the wind tunnel. 🪂$$ WHERE id = 252;
UPDATE activities SET nudge_text = $$Loose an arrow, find your aim — you wanted it. Book the range this week. 🏹$$ WHERE id = 253;

-- Down Migration
ALTER TABLE activities DROP COLUMN IF EXISTS nudge_text;
